<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Testing.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaWeCodes.Application\GaWeCodes.Application.csproj" />
    <ProjectReference Include="..\GaWeCodes.Core\GaWeCodes.Core.csproj" />
    <ProjectReference Include="..\GaWeCodes.Domain\GaWeCodes.Domain.csproj" />
  </ItemGroup>

</Project>
