<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\GaWeCodes.Application\GaWeCodes.Application.csproj" />
    <ProjectReference Include="..\..\..\src\GaWeCodes.Domain\GaWeCodes.Domain.csproj" />
  </ItemGroup>

</Project>
