<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\DomainOnlyHost\DomainOnlyHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="BuildingBlocks.Application.Cqrs" />
    <Using Include="BuildingBlocks.Application.Persistence" />
    <Using Include="BuildingBlocks.Application.Results" />
    <Using Include="DomainOnlyHost" />
  </ItemGroup>

</Project>
