<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GaWeCodes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="WolverineFx.Marten" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Composition.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.EventSourcing.Marten.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Runtime.Wolverine.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Messaging.RabbitMq.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.PackageConventions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaWeCodes.Persistence\GaWeCodes.Persistence.csproj" />
    <ProjectReference Include="..\GaWeCodes.Persistence.Postgres\GaWeCodes.Persistence.Postgres.csproj" />
    <ProjectReference Include="..\GaWeCodes.Runtime.Wolverine\GaWeCodes.Runtime.Wolverine.csproj" />
  </ItemGroup>

</Project>
