<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\src\GaWeCodes.Persistence.EfCore.Postgres\GaWeCodes.Persistence.EfCore.Postgres.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\src\GaWeCodes.Messaging.RabbitMq\GaWeCodes.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="..\..\VitalSync.Sample.Contracts\VitalSync.Sample.Contracts.csproj" />
    <ProjectReference Include="..\VitalSync.Sample.StateStored.Application\VitalSync.Sample.StateStored.Application.csproj" />
  </ItemGroup>

</Project>
