<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="GaWeCodes.Thessera.Persistence.EfCore.Postgres" />
    <PackageReference Include="GaWeCodes.Thessera.Messaging.RabbitMq" />
    <ProjectReference Include="..\..\VitalSync.Sample.Contracts\VitalSync.Sample.Contracts.csproj" />
    <ProjectReference Include="..\VitalSync.Sample.StateStored.Application\VitalSync.Sample.StateStored.Application.csproj" />
  </ItemGroup>

</Project>
