<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>BuildingBlocks.Infrastructure.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BuildingBlocks.Infrastructure.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Persistence.Adapters.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.EventSourcing.Marten.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Runtime.Wolverine.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Messaging.Wolverine.RabbitMq.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.PackageConventions.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.TestSupport.Containers" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
