<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageTags>postgres;postgresql;npgsql;readiness-check;health-checks</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Core.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Persistence.Marten.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Wolverine.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Messaging.RabbitMq.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Tests.PackageConventions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaWeCodes.Thessera.Core\GaWeCodes.Thessera.Core.csproj" />
  </ItemGroup>

</Project>
