<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>GaWeCodes</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Composition.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.EventSourcing.Marten.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Runtime.Wolverine.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Messaging.RabbitMq.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.PackageConventions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaWeCodes.Composition\GaWeCodes.Composition.csproj" />
  </ItemGroup>

</Project>
