<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\src\GaWeCodes.Domain\GaWeCodes.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GaWeCodes.Domain.Aggregates" />
    <Using Include="GaWeCodes.Domain.Entities" />
    <Using Include="GaWeCodes.Domain.Events" />
    <Using Include="GaWeCodes.Domain.Naming" />
    <Using Include="GaWeCodes.Domain.Rules" />
  </ItemGroup>

</Project>
