<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>GaWeCodes.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GaWeCodes.Core\GaWeCodes.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Core.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.Marten.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Wolverine.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Messaging.RabbitMq.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.PackageConventions.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Tests.Containers" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
