// <auto-generated />
using System;
using GaWeCodes.Thessera.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalSync.Sample.StateStored.Infrastructure.Write;

#nullable disable

namespace VitalSync.Sample.StateStored.Infrastructure.Migrations.Write
{
    [DbContext(typeof(WidgetWriteDbContext))]
    [Migration("20260804081846_AddWidgetParts")]
    partial class AddWidgetParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalSync.Sample.StateStored.Domain.WidgetState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RenameCount")
                        .HasColumnType("integer")
                        .HasColumnName("rename_count");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("widgets", (string)null);
                });

            modelBuilder.Entity("VitalSync.Sample.StateStored.Domain.WidgetState", b =>
                {
                    b.OwnsMany("VitalSync.Sample.StateStored.Domain.WidgetPart", "Parts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.Property<Guid>("widget_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("widget_id");

                            b1.ToTable("widget_parts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("widget_id");
                        });

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
