// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalSync.Sample.StateStored.Infrastructure.Write;

#nullable disable

namespace VitalSync.Sample.StateStored.Infrastructure.Migrations.Write
{
    [DbContext(typeof(WidgetWriteDbContext))]
    partial class WidgetWriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalSync.Sample.StateStored.Domain.WidgetState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RenameCount")
                        .HasColumnType("integer")
                        .HasColumnName("rename_count");

                    b.HasKey("Id");

                    b.ToTable("widgets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
