<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="9.20.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="WolverineFx.RabbitMQ" Version="6.23.0" />
    <PackageReference Include="WolverineFx.Marten" Version="6.23.0" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.23.0" />
    <PackageReference Include="WolverineFx.Postgresql" Version="6.23.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BuildingBlocks.Infrastructure.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>
