<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BuildingBlocks.Infrastructure.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Persistence.Adapters.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.EventSourcing.Marten.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Runtime.Wolverine.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Messaging.Wolverine.RabbitMq.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.PackageConventions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
  </ItemGroup>
</Project>
