<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BuildingBlocks.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="WolverineFx.Marten" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BuildingBlocks.Infrastructure.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Persistence.Adapters.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.EventSourcing.Marten.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Runtime.Wolverine.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.Messaging.Wolverine.RabbitMq.Tests" />
    <InternalsVisibleTo Include="BuildingBlocks.PackageConventions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Persistence.Adapters\BuildingBlocks.Persistence.Adapters.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Persistence.Postgres\BuildingBlocks.Persistence.Postgres.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Runtime.Wolverine\BuildingBlocks.Runtime.Wolverine.csproj" />
  </ItemGroup>

</Project>
