<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Thessera\src\GaWeCodes.Thessera.Application\GaWeCodes.Thessera.Application.csproj" />
    <ProjectReference Include="..\VitalSync.Sample.StateStored.Domain\VitalSync.Sample.StateStored.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GaWeCodes.Thessera.Application.Cqrs" />
    <Using Include="GaWeCodes.Thessera.Application.Persistence" />
    <Using Include="GaWeCodes.Thessera.Application.Results" />
  </ItemGroup>

</Project>
