<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Core.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Persistence.Marten.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Wolverine.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Messaging.RabbitMq.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Thessera.Tests.PackageConventions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaWeCodes.Thessera.Core\GaWeCodes.Thessera.Core.csproj" />
    <ProjectReference Include="..\GaWeCodes.Thessera.Wolverine\GaWeCodes.Thessera.Wolverine.csproj" />
  </ItemGroup>

</Project>
