<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="GaWeCodes.Thessera.Domain" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GaWeCodes.Thessera.Domain.Aggregates" />
    <Using Include="GaWeCodes.Thessera.Domain.Entities" />
    <Using Include="GaWeCodes.Thessera.Domain.Events" />
    <Using Include="GaWeCodes.Thessera.Domain.Naming" />
    <Using Include="GaWeCodes.Thessera.Domain.Rules" />
  </ItemGroup>

</Project>
