<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\src\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\VitalSync.Sample.EventSourced.Domain\VitalSync.Sample.EventSourced.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="BuildingBlocks.Application.Cqrs" />
    <Using Include="BuildingBlocks.Application.Persistence" />
    <Using Include="BuildingBlocks.Application.Results" />
  </ItemGroup>

</Project>
