<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\src\GaWeCodes.Application\GaWeCodes.Application.csproj" />
    <ProjectReference Include="..\VitalSync.Sample.EventSourced.Domain\VitalSync.Sample.EventSourced.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GaWeCodes.Application.Cqrs" />
    <Using Include="GaWeCodes.Application.Persistence" />
    <Using Include="GaWeCodes.Application.Results" />
  </ItemGroup>

</Project>
