<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GaWeCodes.Core.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.EfCore.Postgres.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Persistence.Marten.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Wolverine.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.Messaging.RabbitMq.Tests" />
    <InternalsVisibleTo Include="GaWeCodes.PackageConventions.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GaWeCodes.Application\GaWeCodes.Application.csproj" />
    <ProjectReference Include="..\GaWeCodes.Domain\GaWeCodes.Domain.csproj" />
  </ItemGroup>
</Project>
